# Generated by Django 3.1.6 on 2021-02-06 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_advertiser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='hour_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.PositiveIntegerField(default=0)),
                ('view', models.PositiveIntegerField(default=0)),
                ('time', models.DateTimeField(default=datetime(2021, 2, 6, 12, 58, 29, 758504))),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad')),
            ],
        ),
        migrations.CreateModel(
            name='daily_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.PositiveIntegerField(default=0)),
                ('view', models.PositiveIntegerField(default=0)),
                ('time', models.DateTimeField(default=datetime(2021, 2, 6, 12, 58, 29, 758169))),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad')),
            ],
        ),
    ]
